### ISSUE TITLE
Feature: User can generate a new country and flag image

### ISSUE THREAD

**Issue by francismanalang** [francismanalang/flash-flags#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

 User can generate a new country and a flag image
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Users will be able to click an image of a globe and start generating random countries along with their flag.

Create a country generator that will show a new random country when the user clicks the globe or 'next' button.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="440" alt="Screen Shot 2022-08-02 at 11 23 25 AM" src="https://user-images.githubusercontent.com/101234537/182446609-d15ff372-b083-4016-8e1c-a021550cd096.png">
<img width="440" alt="Screen Shot 2022-08-02 at 11 23 38 AM" src="https://user-images.githubusercontent.com/101234537/182446641-1b99cd11-b463-4584-b1b0-422d984cd64d.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a navbar that goes along the entire width of the page.
- [x] Add the name of the application on the navbar.
- [x] Add the image of the globe in the middle of the page along with the label title.
- [x] Once the globe is clicked, make the label and globe hidden.
- [x] Create the country name and flag display and show it once the globe page is hidden.
- [x] Generate a new random country once the "next" button is clicked
- [x] Make the app name into a button that will show the globe page when clicked.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
