### ISSUE TITLE
Feature: User can save a country

### ISSUE THREAD

**Issue by francismanalang** [francismanalang/flash-flags#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can save a country and flag into a list.

User can save a country
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
A "SAVE" button will be added that will allow the user to save a country that can be viewed later.

Create a "SAVE" button that will take the user to a "Countries List" that will show all the countries that have been saved. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="490" alt="Screen Shot 2022-08-02 at 11 41 57 AM" src="https://user-images.githubusercontent.com/101234537/182449789-8a4f15f7-9fd0-451a-bffe-e25bfdf07f1e.png">
<img width="649" alt="Screen Shot 2022-08-02 at 4 48 06 PM" src="https://user-images.githubusercontent.com/101234537/182495524-c0a955fe-4044-424c-a899-48ad9386df8d.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a "SAVE" button in the "Country generator" view.
- [x] Add a click event to the saved button that prepends the country name and flag image into data.saved and view swaps into a "Countries List" view.
- [x] Add a DOM Tree that generates saved flags into rows in the "Countries List" page. 
- [x] Add a study button into the bottom of the "Countries List" view.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
