### ISSUE TITLE
Feature: User can view the list of countries

### ISSUE THREAD

**Issue by francismanalang** [francismanalang/flash-flags#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
There will be a list button added to the navbar the will allow a user to view the list of countries they have saved.

User can view the list of countries
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
A "List" button will be added to the navbar that a user can click that will take them to a "Countries List" page. 

Create a "List" button that will make the display page hidden and show the list page.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="400" alt="Screen Shot 2022-08-03 at 10 28 45 AM" src="https://user-images.githubusercontent.com/101234537/182671980-a35dc918-e774-4ada-aacd-476d69716f81.png">
<img width="458" alt="Screen Shot 2022-08-03 at 10 29 37 AM" src="https://user-images.githubusercontent.com/101234537/182671998-0b51f752-30e0-4d61-a3cf-370103f4b7c1.png">
<img width="456" alt="Screen Shot 2022-08-03 at 10 29 45 AM" src="https://user-images.githubusercontent.com/101234537/182672006-cf901b51-657b-44a6-91f0-e8aa97943f67.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a list button to the right side of the navbar
- [x] Add a click event to the list button that will view swap to the "Countries List" page
- [x] If there are no countries on the countries list, hide the study button and show text letting the user know they have no flags to study. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
