### ISSUE TITLE
Feature: User can study the countries list

### ISSUE THREAD

**Issue by francismanalang** [francismanalang/flash-flags#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
Users will have a "STUDY" button on the countries list that will allow them to study saved countries in a flashcards format.

User can study the countries list
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Clicking the "STUDY" button will take take users to the "Study view" where they can test their knowledge of the flags they have chosen to save.

Create a "STUDY" button that will make the countries list hidden and show the study page where users can:
1. Display the flag. 
2. Get the answer to the flag
3. A "BACK" button to go back to the flag view
4. A "NEXT" button to study the next country.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="491" alt="Screen Shot 2022-08-03 at 12 41 31 PM" src="https://user-images.githubusercontent.com/101234537/182695413-0b5c0189-dc4c-4303-8741-32631de0fb58.png">
<img width="402" alt="Screen Shot 2022-08-03 at 12 42 18 PM" src="https://user-images.githubusercontent.com/101234537/182695430-9bc4e0e9-a1e6-4182-bb23-a76c9de8a1eb.png">
<img width="406" alt="Screen Shot 2022-08-03 at 12 42 32 PM" src="https://user-images.githubusercontent.com/101234537/182695439-59924544-19c2-436d-98c0-d6a7411adc17.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a "Study view" in HTML that only shows the flag image and an "ANSWER" button
- [x] Add another component to the study view that will show the country flag and country name when the answer button is clicked. 
- [x] Add a "BACK" and "NEXT" button under the study view.
- [x] Create a click event on the back button that will swap back to the study view with only the flag image and answer button.
- [x] Create a click event on the "NEXT" button that will go to the next flag in the data.saved array. 
- [x] Create a click event on the "STUDY" button that will view swap to the "Study view".
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
