### ISSUE TITLE
Feature: User can delete a country they have learned

### ISSUE THREAD

**Issue by francismanalang** [francismanalang/flash-flags#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
Users will be able to delete a country they no longer want on their study list.

User can delete a country they have learned
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User will be able to delete a country from the countries list once it has been committed to memory.

Create a delete button next to each flag in the countries list that will display a modal with the options "CANCEL" or "DELETE".
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="402" alt="Screen Shot 2022-08-04 at 10 36 52 AM" src="https://user-images.githubusercontent.com/101234537/182915165-26c23920-bbbb-4e20-9bee-1554d2530703.png">
<img width="404" alt="Screen Shot 2022-08-04 at 10 37 02 AM" src="https://user-images.githubusercontent.com/101234537/182915200-28b5f080-7d76-410c-a71c-016a77291d99.png">
<img width="400" alt="Screen Shot 2022-08-04 at 10 37 12 AM" src="https://user-images.githubusercontent.com/101234537/182915210-ce73221e-b264-4c23-bbee-15becf9c8b96.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a delete icon in the dom tree function that will appear for every flag in the countries list
- [x] Add an entry id to every flag that is saved in data.saved
- [x] Add a click event to the delete icon that will show the modal display on top of the "countries list" view
- [x] Within the modal, add a cancel and delete button
- [x] If the cancel button is clicked, the modal will be hidden
- [x] if the delete button is clicked, delete the flag from the countries list. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
